---
layout:     post
title:      Pytorch 解决加载模型导入模型出错
subtitle:   RuntimeError:Error(s) in loading state_dict for DataParallel
date:       2019-12-26
author:     LZY
header-img: img/whatisnext.jpg
catalog: true
tags:
    - 深度学习
    - Pytorch
---

# Problem 1

完整报错信息：
RuntimeError:Error(s) in loading state_dict for DataParallel：
Unexpected key(s) in state_dict:“module.resnet.bn1.num_batches_tracked”,"module.resnet.layer1.0.bn1.num_batches_tracked"等等

说明你训练模型和测试加载模型所使用的环境不一致

## 解决方法

```python

model.load_state_dict(checkpoint['state_dict']) # 原代码

model.load_state_dict(checkpoint['state_dict'],False) # 修改处

```

